# Generated by Django 4.2.11 on 2024-06-02 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoPosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
                ('post_title', models.TextField(blank=True, default='', null=True)),
                ('post_content', models.TextField(blank=True, default='', null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('access_count', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': '投稿',
            },
        ),
    ]
